# CHAPTER 12 - NumPy


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

a

array([1, 2, 3, 4, 5, 6])

In [2]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
print(b[0])

[1 2 3 4]


In [4]:
a = np.array([2,3,4])

a


array([2, 3, 4])

In [5]:
b = np.array([1.2, 3.5, 5.1])

b

array([1.2, 3.5, 5.1])

In [6]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('float64')

In [8]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [9]:
a = np.array([1,2,3,4])  # RIGHT

a

array([1, 2, 3, 4])

In [10]:
b = np.array([(1.5,2,3), (4,5,6)])

b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Or an array filled with 1’s:

np.ones(2)

array([1., 1.])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.zeros(3)


array([0., 0., 0.])

In [16]:
rng = np.random.default_rng(0)

rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
rng.random((3,2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

In [20]:
# Create an empty array with 2 elements
np.empty( (2,3) )                                 # uninitialized

array([[0.01652764, 0.81327024, 0.91275558],
       [0.60663578, 0.72949656, 0.54362499]])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
# starts from 2, ends before 9, step size 2
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [23]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
x = np.ones(2, dtype=np.int64)

x

array([1, 1], dtype=int64)

In [26]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [28]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [31]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [33]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6]])

In [35]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [37]:
array_example.ndim

3

In [38]:
array_example.size

24

In [39]:
array_example.shape

(3, 2, 4)

In [40]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [41]:
b = a.reshape(3, 2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [42]:
np.reshape(a, newshape = (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
np.reshape(a, newshape = (2,3), order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.reshape(a, newshape = (2,3), order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [45]:
np.reshape(a, newshape = (6), order = 'F')

array([0, 1, 2, 3, 4, 5])

In [46]:
a = np.array([1, 2, 3, 4, 5, 6])

a

array([1, 2, 3, 4, 5, 6])

In [47]:
a.shape

(6,)

In [48]:
a2 = a[np.newaxis, :]

a2

array([[1, 2, 3, 4, 5, 6]])

In [49]:
a2.shape

(1, 6)

In [50]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [51]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [52]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [54]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [55]:
data = np.array([1, 2, 3])

In [56]:
data [1]

2

In [57]:
data[0]

1

In [58]:
data[0:2]

array([1, 2])

In [59]:
data[1:]

array([2, 3])

In [60]:
data[-2:]

array([2, 3])

In [61]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
print(a[a<5])

[1 2 3 4]


In [63]:
five_up = (a >= 5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [64]:
divisible_by_two = a[a%2 == 0]

print(divisible_by_two)

[ 2  4  6  8 10 12]


In [65]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [66]:
five_up = (a > 5) | (a == 5)

print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [68]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b = np.nonzero(a < 5)

print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [70]:
print(a[b])

[1 2 3 4]


In [71]:
not_there = np.nonzero(a == 42)

print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [72]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [74]:
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

In [75]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [76]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [77]:
x = np.arange(1, 25).reshape(2, 12)

x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [78]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [79]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [80]:
a = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])

b = a            # no new object is created

b is a           # a and b are two names for the same ndarray object

True

In [81]:
def f(x):
     print(id(x))
        
id(a)                           # id is a unique identifier of an object

2445066119408

In [82]:
f(a) # The number in the output may vary

2445066119408


In [83]:
c = a.view()

c is a

False

In [84]:
c.base is a                        # c is a view of the data owned by a

True

In [85]:
c.flags.owndata

False

In [86]:
c = c.reshape((2, 6))                      # a's shape doesn't change

a.shape

(3, 4)

In [87]:
c[0, 4] = 1234                      # a's data changes

a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [88]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:, 1:3]"

s[:] = 10           # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10

a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [89]:
d = a.copy()                          # a new array object with new data is created

d is a

False

In [90]:
d.base is a                           # d doesn't share anything with a

False

In [91]:
d[0,0] = 9999

a                          # d doesn't change anything within a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [92]:
a = np.arange(int(1e8))

b = a[:100].copy()

del a                                           # the memory of ``a`` can be released.