# Chapter 13 - NumPy Operations

In [1]:
import numpy as np

data = np.array([1, 2])
ones = np.ones(2, dtype=int)

data + ones

array([2, 3])

In [2]:
data - ones

array([0, 1])

In [3]:
data * data

array([1, 4])

In [4]:

data / data


array([1., 1.])

In [5]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [6]:
b = np.array([[1, 1], [2, 2]])

In [7]:
b.sum(axis=0)

array([3, 3])

In [8]:
b.sum(axis=1)

array([2, 4])

In [9]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

b

array([0, 1, 2, 3])

In [10]:
c = a-b

c

array([20, 29, 38, 47])

In [11]:
b*2

array([0, 2, 4, 6])

In [12]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [13]:
a<35

array([ True,  True, False, False])

In [14]:
A = np.array( [[1,1],
                [0,1]] )
B = np.array( [[2,0],
                [3,4]] )


A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [15]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [16]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [17]:
a = np.array([(1,2,3), (4,5,6)])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a.sum()

21

In [19]:
a.min()

1

In [20]:
a.max()

6

In [21]:
b = np.arange(12).reshape(3,4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [23]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [24]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [25]:
B = np.arange(3)

B

array([0, 1, 2])

In [26]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [27]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [28]:
C = np.array([2., -1., 4.])

np.add(B, C)

array([2., 0., 6.])

In [29]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [30]:
data.max()

2.0

In [31]:
data.min()

1.0

In [32]:
data.sum()

3.0

In [33]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [34]:
a.sum()

4.8595784

or

In [35]:
a.min()

0.05093587

In [36]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [37]:
data = np.array([[1, 2], [3, 4]])

data

array([[1, 2],
       [3, 4]])

In [38]:
data = np.array([[1,2],[3,4],[5,6]])

data[0,1]         # first row second column

2

In [39]:
data[1:3]        #second to third row and all columns

array([[3, 4],
       [5, 6]])

In [40]:
data[0:2, 0]      #first to second row and first column

array([1, 3])

In [41]:
data.min()

1

In [42]:
data.max()

6

In [43]:
data.sum()

21

In [44]:
data.max(axis=0)

array([5, 6])

In [45]:
data.max(axis = 1)

array([2, 4, 6])

In [46]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

data+ones

array([[2, 3],
       [4, 5]])

In [47]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [48]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [49]:
unique_values = np.unique(a)

print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [50]:
unique_values, indices_list = np.unique(a, return_index=True)

print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [51]:
np.unique(a, return_index=True)     # This gives two arrays, one the unique values and the other is indices

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [52]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [53]:
# This gives 3 arrays, one the unique values, 2nd is indices, 3rd is count of unique values

np.unique(a, return_index=True,return_counts=True ) 

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [54]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [55]:
unique_values = np.unique(a_2d)

print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [58]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
print(indices)

[0 1 2]


In [60]:
print(occurrence_count)

[2 1 1]


In [61]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [63]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
arr = np.arange(6).reshape((2, 3))

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can reverse it with:

In [68]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [69]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
reversed_arr = np.flip(arr_2d)

print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [71]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

print(reversed_arr_rows)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [72]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [73]:
arr_2d[1] = np.flip(arr_2d[1])

print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [74]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [75]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
a1 = x.flatten()

a1[0] = 99

print(x)    # Original Array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [79]:
a2 = x.ravel()

a2[0] = 95

print(x)    # Original Array

[[95  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
print(a2)     # New array which is flattened

[95  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
a = np.array([1, 2, 3, 4, 5, 6])

You can save it as "filename.npy" with:

In [82]:
np.save('filename', a)

Now if you go in your base folder, you will find a new file named "filename.npy". 

You can use np.load() to reconstruct your array.

In [83]:
b = np.load('filename.npy')

Now lets check the array by running:

In [84]:
print(b)

[1 2 3 4 5 6]


In [85]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can easily save it as a `.csv` file with the name "new_file.csv" like this:

In [86]:
np.savetxt('new_file.csv', csv_arr)

In [87]:
 np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])